### ISSUE TITLE
Error when trying to list entities

### ISSUE THREAD

**Issue by joaohelis** [conwetlab/ngsijs#12]
```
       <script type="text/javascript">
		$(document).ready(function() {
			console.log('Ready disparado');
			window.connection = new NGSI.Connection("http://ip_address:1026");

			console.log(connection);
			connection.v2.listEntities().then((result) => {
			    response.results.forEach((entity) => {
			        console.log(entity.id);
			    });
			});
		});
	</script>
```

```
Uncaught TypeError: this.makeRequest is not a function
    at NGSIConnection.makeJSONRequest2 (NGSI.js:206)
    at V2.listEntities (NGSI.js:2604)
    at HTMLDocument.<anonymous> (index.html:15)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.I (jquery.min.js:2)
```

**Comment by aarranz** [comment]
Sorry for not answering before. The exception raised by your code should be fixed by commit db122c2, but probably you will still have problems. I'm in the process to update the documentation, but as a summary, you will need to use orion context broker v1.9.0+ (not released yet, see telefonicaid/fiware-orion#501) or using some proxy to enable CORS, e.g. a [cors-anywhere](https://www.npmjs.com/package/cors-anywhere) or [pep](https://github.com/ging/fiware-pep-proxy) proxy. 

I will try to finish this documentation ASAP then I will make a release.

Best regards.
